# Generated by Django 5.0.2 on 2026-07-01 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequence_analyzer', '0004_predictionmodel_sequencesubmission_prediction_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequencesubmission',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
